name: 'ActionServerless'
description: Use GitHub Actions to create a serverless service
inputs:
  filepath:  # id of input
    description: 'A file path where to read source code'
    required: false
runs:
  using: "composite"
  steps:
    - id: run-funcs
      run: |
        python3 -m pip install gitfx
        python3 -m gitfx ${{ inputs.filepath }}
      shell: bash
branding:
  icon: 'cloud-lightning'
  color: 'purple'
