name: Test run funcs

on: [push]

jobs:
  test_ruby_func:
    runs-on: ubuntu-latest
    name: A job to test run functions
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Clear result files ahead for test
      run: rm -rf test/result
    - name: Run funcs
      uses: ./
      with:
        filepath: test/func_examples
    - name: Check if result files exist
      run: |
        cd test/result

        files=(elixir_string

               golang.json
               golang_string

               haskell.json

               node.json
               node_string

               perl.json

               php.json

               python.json
               python_second.json
               python_string

               ruby.json
               ruby_second.json

               test_before_script

               bash_string
               bash.json
              )

        status=0

        for f in "${files[@]}"
        do
          if [ ! -f $f ]; then
              echo "File not found: $f"
              status=1
          fi
        done

        exit $status
